### ISSUE TITLE
Store strings to internal flash memory?

### ISSUE THREAD

**Issue by noukee** [platformio/platform-nordicnrf52#106]
Hi,

With IDE Arduino I can't find any library to store data in the internal flash memory with nrf52832

May anyone help me? 

Thanks in advance!

**Comment by cujomalainey** [comment]
Isnt that what PROGMEM is for?

**Comment by valeros** [comment]
Hi @noukee ! This repo is not the right place to ask such questions. Please open an issue in an appropriate repository of the Arduino core you're using.
