### ISSUE TITLE
Add support for board Laird BL653 DVK

### ISSUE THREAD

**Issue by tcwalther** [platformio/platform-nordicnrf52#122]
It would be great if support for the Laird BL653 DVK board was added. 🙏🏻 
https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bl653-series-bluetooth-51-802154-nfc-module

**Comment by dberlin** [comment]
Zephyr supports this board as variant bl653_dvk. 
@tcwalther Should be some simple modifications (change the zephyr variant listed, etc) of the https://github.com/platformio/platform-nordicnrf52/blob/develop/boards/nrf52833_dk.json json if you want board json to put in a project in the meanwhile.
