### ISSUE TITLE
Example code of a library that has Kconfig options

### ISSUE THREAD

**Issue by lexologe** [platformio/platform-nordicnrf52#135]
Hello, I am trying to build a library that has Kconfig options. The library should be included by `lib_deps = ` in `platformio.ini` and should show it's Kconfig options in `pio run -t menuconfig`.
Can someone help me to find a working example library?

Thanks,
Alex

**Comment by valeros** [comment]
Hi @lexologe ! The current Zephyr integration doesn't support adding Zephyr modules as dependencies in `lib_deps`. Instead you need to use the `ZEPHYR_EXTRA_MODULES` variable in your `CMakeLists.txt`, see the [docs](https://docs.platformio.org/en/latest/frameworks/zephyr.html#zephyr-modules) for more detailed information.
