### ISSUE TITLE
OpenOCD upload

### ISSUE THREAD

**Issue by cimbalo** [platformio/platform-nordicnrf52#17]
Hi,
since 0c1d17dbcc5ef7ba0d2febefac4e26d5a8fa1046 I'm unable to upload using OpenOCD tool.
Is it still possible?
Is a PR, whitch reintroduce openocd as an available uploader tool, welcomed?

**Comment by ivankravets** [comment]
What is your board?

**Comment by cimbalo** [comment]
I'm currently using a custom nRF52832 board.
I'm uploading the firmware using Bus Blaster v4 as an KT-Link compatible SWD programmer.
Here is an example on a different MCU: https://gist.github.com/natevw/14d1f1fe669ec6e201c5

**Comment by ivankravets** [comment]
You need a custom upload tool, see example http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html
