### ISSUE TITLE
compilation color output is missing

### ISSUE THREAD

**Issue by fariouche** [platformio/platform-nordicnrf52#183]
Hello,

I would help to have the color output from ninja. However, the minimum version of ninja that supports color outputs is 1.9.0.
Unfortunately, for linux, the tool-ninja package is 1.7.0 in the registry.

As a test, I modified the builder to add env.AppendENVPath('CLICOLOR_FORCE', '1')
and used my PC ninja executable instead of tool-ninja, and it worked!
Now the following message from the compiler `defined but not used [-Wunused-variable]` with "-Wunused-variable" in nice color.

Can we have an up to date ninja executable available in the registry please? (Mine is 1.11.1)

Thanks

**Comment by fariouche** [comment]
exact, I got confused... it's because we use a ninja script to build mcuboot from a custom script... it's not related to nordicnrf52 platform.

**Comment by valeros** [comment]
Closing as not related to the to nordicnrf52 platform.
