### ISSUE TITLE
Update 2.4.1 breaks build_flags 

### ISSUE THREAD

**Issue by alejmolinas** [platformio/platform-nordicnrf52#20]
The update ignores std flags build_flags on platformio.ini

For example:

```
[env:nrf52_dk]
platform = nordicnrf52
board = nrf52_dk
framework = mbed
build_flags = -std=c++11 -D PIO_FRAMEWORK_MBED_RTOS_PRESENT
```
only sets the RTOS_PRESENT macro and doesn't change the c++ standard.
In the c_cpp_properties,json created by those flags I have
```
“intelliSenseMode”: “clang-x64”,
“cStandard”: “c99”,
“cppStandard”: “c++98”,
“compilerPath”: “C:/Users/Ale/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe”
```
This of course breaks a lot of builds based on other-than-default c++ standard (I believe).
I've also written about this issue [here](https://community.platformio.org/t/build-flags-not-recognizing-std-c-11-after-updating-nrf52dk-platform/5184)

**Comment by ivankravets** [comment]
mbed specifies own standard. You can check that with `pio run -v`. Use `build_unflag` to remove default mbed's flags:

```
[env:nrf52_dk]
platform = nordicnrf52
board = nrf52_dk
framework = mbed
build_flags = -std=c++11 -D PIO_FRAMEWORK_MBED_RTOS_PRESENT
build_unflags = -std=gnu++98
```
