### ISSUE TITLE
Arduino Core for Nordic Semiconductor nRF5 based boards

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-nordicnrf52#3]
# Moved from https://github.com/platformio/platformio-core/issues/868

Arduino Core:

* https://github.com/sandeepmistry/arduino-nRF5

/cc @amq, @jrobeson, @colinblake, @boneskull, @profra, @PierreKircher, @sabas1080, @danielpgross, @cujomalainey

**Comment by fab33** [comment]
+1

**Comment by mtiutiu** [comment]
Is it possible to make the **sandeepmistry arduino-nRF5 core** available for **platform-nordicnrf51** too? It seems that this core is more up to date and working well so far as I'm using it on some projects. And to be honest I want to get rid of Arduino IDE - this nrf5 core is all that keeps me using it for now. Thanks a lot.

**Comment by ivankravets** [comment]
@mtiutiu We are working on that. Please follow us on Twitter to stay tuned https://twitter.com/PlatformIO_Org

**Comment by cujomalainey** [comment]
@ivankravets the package by sandeepmistry only supports BLE soft devices, how hard would it be to integrate a variant (that I am working on) that also supports the ANT stack.

**Comment by ivankravets** [comment]
@cujomalainey could you give some links?

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-nordicnrf52/releases/tag/v1.2.0
