### ISSUE TITLE
Adafruit Feather NRF52832 function delay() causes crash.

### ISSUE THREAD

**Issue by Splitframe** [platformio/platform-nordicnrf52#35]
The following code crashes with the Adafruit Feather NRF52832 and "Test B" is not shown.
A possible workaround is to use delayMicroseconds().
Edit: my platformio.ini:

```
[env:adafruit_feather_nrf52832]
platform = nordicnrf52
board = adafruit_feather_nrf52832
framework = arduino
```
The code:
```
#include <main.h>

int main() {
  Serial.begin(9600);
  Serial.println(F("Test A"));
  delay(100);
  Serial.println(F("Test B"));
}
```

**Comment by jeremypoulter** [comment]
I am supprised that even compiles ;-) the Adafruit BSP is an Arduino core and as such you should use `setup` and `loop` not `main`.

The Adafruit BSP uses FreeRTOS under the hood the `main` in the BSP launches a task and `setup` and `loop` are call in that task. `delay` then puts that task to sleep.

Calling it like you have there the RTOS is not setup nor are you calling `delay` in task.

**Comment by Splitframe** [comment]
Oh! I am sorry,
I wasn't aware of this. I used to just pump normal cpp into arduinos.
Thank you.
