### ISSUE TITLE
Adafruit Feather NRF52 BSP update to 0.10.1?

### ISSUE THREAD

**Issue by wb8wka** [platformio/platform-nordicnrf52#41]
When will the PlatformIO BSP for the Adafruit NRF52 be updated from 0.9.3 to 0.10.1?

**Comment by jeremypoulter** [comment]
@ivankravets What is the best process for updating? I assume you need to create a new package of the Adafruit BSP then a PR can be created with the required updates?

**Comment by ivankravets** [comment]
@jeremypoulter done! https://bintray.com/beta/#/platformio/dl-packages/framework-arduinoadafruitnrf52/1.1001.0?tab=files

Please note that new boards were added in the new release. It would be good to have them in PlatformIO too.

**Comment by wb8wka** [comment]
@ivankravets wow thank you.   Excuse the newbie question, as day before yesterday was my first use of PlatformIO, but I'd just replace this directory:

C:\Users\kingr\.platformio\packages\framework-arduinoadafruitnrf52

with this: framework-arduinoadafruitnrf52-1.1001.0.tar.gz\  **framework-arduinoadafruitnrf52** 
 -1.1001.0.tar\      (keeping the same directory structure and name)

**Comment by ivankravets** [comment]
> PlatformIO, but I'd just replace this directory:

Does it work?

**Comment by wb8wka** [comment]
I'll be trying it later this evening, I will let you know.

**Comment by wb8wka** [comment]
@ivankravets 

Sorry for the delay. I deleted everything in:

C:\Users\kingr.platformio\packages\framework-arduinoadafruitnrf52

and then replaced it with the contents of the tar.gz file you attached.

then did a build and all seemed fine but I noticed it created a director that contained the 0.9.3 BSP:

C:\Users\kingr\.platformio\packages\framework-arduinoadafruitnrf52@1.903.0

and on closer examination was building with 0.9.3.  I deleted that directory and did a clean and it ended up downloading the 0.9.3 files again and recreating that directory.

**Comment by wb8wka** [comment]
Oh, and this was with core 3.6.6

**Comment by wb8wka** [comment]
Any thoughts?

**Comment by jeremypoulter** [comment]
Was looking at this yesterday, there are a few changes needed in the Platform IO side of things. Update to get the new package and currently the version numbers are hard coded, doing an update to read from the framework. Plus adding the additional boards ;-)

**Comment by wb8wka** [comment]
So perhaps in the next release of PlatformIO?  I don't need the features of 0.10.1 at this point, was more curious if it could be incorporated sooner.

**Comment by ivankravets** [comment]
Please re-test with upstream version https://docs.platformio.org/en/latest/platforms/nordicnrf52.html#upstream

**Comment by wb8wka** [comment]
@ivankravets yes, that works. Had to reinstall GitCLient and restart platformIO but worked fine after that.

Thanks!
