### ISSUE TITLE
Add support for the RakWireless Rak811 Family

### ISSUE THREAD

**Issue by Phando** [platformio/platform-nordicnrf52#77]
Please look into these STM32 boards, they are awesome but their development platform is ridiculously complicated. There is an online compiler you have to send zip files. 

Specifically, it would be nice to use the boards over usb and serial by default.
 Below is my platformio.ini, I am overriding the STM programmer to use the one that is in the Arduino install.

```
[env:rak811_tracker]
platform = ststm32
board = rak811_tracker
framework = arduino

upload_port = cu.usbserial-141220
;upload_port = cu.SLAB_USBtoUART

monitor_speed = 115200
upload_protocol = serial
upload_command = /Users/jandolina/Library/Arduino15/packages/STM32/tools/STM32Tools/1.3.2/tools/macosx/stm32CubeProg 1 $SOURCE $UPLOAD_PORT -s

```

The boards in question:
https://store.rakwireless.com/products/rak811-lpwan-evaluation-board
https://store.rakwireless.com/products/rak5205-lpwan-tracker

**Comment by valeros** [comment]
This repository is for `nordicnrf52` platform, not `ststm32`. Besides, support for rak811 was already added here https://github.com/platformio/platform-ststm32/issues/86
