### ISSUE TITLE
Add nrf52833_DK 

### ISSUE THREAD

**Issue by Olfox59** [platformio/platform-nordicnrf52#78]
https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52833-DK

**Comment by kb-consulting** [comment]
+1

**Comment by brandonOpener** [comment]
+1 for nrf52833.  I'm working with the BL653 dev kit, chip support would be excellent, even if it takes some finagling to get my board up and running.

**Comment by MarkusBansky** [comment]
Is there any update on this issue, this board is already becoming popular and setting up the Mesh sample using board preset for nRF52840 for example does not work. 

Does anyone have any example of how to set up the nRF52833 DK project?
