### ISSUE TITLE
adafruit_itsybitsy_nrf52840 has no JLink

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-nordicnrf52#82]
See discussion in https://community.platformio.org/t/unable-to-debug-adafruit-itsybitsy-nrf52840/14430.

The Adafruit schematics and pinouts do not show the existance of a JLink probe on the board, just the nRF chip. SWCLK and SWDIO are just solder-pads on the board for an external debugger.

Thus 

https://github.com/platformio/platform-nordicnrf52/blob/a9df05fc469586673932e0365b14344bd475b0e1/boards/adafruit_itsybitsy_nrf52840.json#L49-L51

must be corrected.

**Comment by valeros** [comment]
Thanks, fixed!
