### ISSUE TITLE
Add support for Adafruit CLUE

### ISSUE THREAD

**Issue by jhmaloney** [platformio/platform-nordicnrf52#85]
I'd like to request support for the Clue, a new nrf52 board from Adafruit (https://www.adafruit.com/product/4500) that is supported by the Adafruit nrf52 Arduino package (cluenrf52840 in framework-arduinoadafruitnrf52/boards.txt).

I am currently using the local board definition below, as suggested by maxgerhardt in https://community.platformio.org/t/adafruit-clue-board/14743/2. That is working fine for me but it would be great to make it official.

Thank you!

{
  "build": {
    "arduino":{
      "ldscript": "nrf52840_s140_v6.ld"
    },
    "core": "nRF5",
    "cpu": "cortex-m4",
    "extra_flags": "-DARDUINO_NRF52840_CLUE -DNRF52840_XXAA -DNRF52840_CLUE",
    "f_cpu": "64000000L",
    "hwids": [
      [
        "0x239A",
        "0x8072"
      ],
      [
        "0x239A",
        "0x0072"
      ],
      [
        "0x239A",
        "0x0071"
      ],
      [
        "0x239A",
        "0x8071"
      ]
    ],
    "usb_product": "CLUE",
    "mcu": "nrf52840",
    "variant": "clue_nrf52840",
    "bsp": {
      "name": "adafruit"
    },
    "softdevice": {
      "sd_flags": "-DS140",
      "sd_name": "s140",
      "sd_version": "6.1.1",
      "sd_fwid": "0x00B6"
    },
    "bootloader": {
      "settings_addr": "0xFF000"
    }
  },
  "connectivity": [
    "bluetooth"
  ],
  "debug": {
    "jlink_device": "nRF52840_xxAA",
    "svd_path": "nrf52840.svd"
  },
  "frameworks": [
    "arduino"
  ],
  "name": "Adafruit CLUE",
  "upload": {
    "maximum_ram_size": 248832,
    "maximum_size": 815104,
    "speed": 115200,
    "protocol": "nrfutil",
    "protocols": [
      "jlink",
      "nrfjprog",
      "nrfutil",
      "stlink"
    ],
    "use_1200bps_touch": true,
    "require_upload_port": true,
    "wait_for_upload_port": true
  },
  "url": "https://www.adafruit.com/product/4500",
  "vendor": "Adafruit"
}

**Comment by cujomalainey** [comment]
Why not send a PR and then save the pio team some work and you get your name in the contributors list?
